### ISSUE TITLE
Test installation on Eclipse Luna.

### ISSUE THREAD

**Issue by generoso** [soctrace-inria/framesoc#100]

**Comment by generoso** [comment]
The first problem (Gantt plugin not installed correctly) was due to the lack of Java Development Tool feature in the environment where the problem was reported.

**Comment by dosimont** [comment]
By the way, did you pay this beer?

**Comment by generoso** [comment]
Solved also the second point. 

That was tricky: you must not set a GridLayout to a TabFolder, and the TabFolder parent composites need GridData with fill property (`new GridData(SWT.FILL, SWT.FILL, true, true)`).

PS: I'll pay my beer with pleasure ;)
