### ISSUE TITLE
Gantt hierarchy cut

### ISSUE THREAD

**Issue by generoso** [soctrace-inria/framesoc#126]
Possibility to cut empty root from the hierarchy.

Example:

````
A
|
--B
   |
   --C
        e e e e e e
```

Becomes:
```
A-B-C
        e e e e e e 
```

**Comment by generoso** [comment]
Issue moved here as a reminder to consider this aspect in the new Gantt (issue #164).

**Comment by dosimont** [comment]
You can go further: take a look on Ocelotl's hierarchy. If a father don't produce events, avoid to show an empty line, which is annoying.
You can represent a hierarchy using this way:

           | D eeeeeeeeeeeeee
A-B-C  |  E eeeee eeeeeee e
           | F e e e             eeee
