### ISSUE TITLE
No feedback on export if disk is full

### ISSUE THREAD

**Issue by alexmrtn** [soctrace-inria/framesoc#139]
When exporting a trace and there is not enough space on the disk to store it, the exporting process starts normally and also ends normally (without error message).
The trace is correctly deleted from the disk releasing the space.
The user can be disappointed to not find his trace file exported and having no feedback message.

**Comment by ycorre** [comment]
This issue is importer dependent: the following importer handles this problem by reporting a "Disk I/O error" in a message dialog box : PJ_dump, paje, OTF2, CTF. Only Gstreamer seems to reporting an error that do not relate to the the disk being full (cf. issue #46 at framesoc.importers).
