### ISSUE TITLE
Changing timeunit when importing traces

### ISSUE THREAD

**Issue by stanisic** [soctrace-inria/framesoc#149]
I see that this part have been changed so users can choose the time unity. However, the way it is implemented at the moment is not intuitive. I understand that the most logical solution (where user would just choose the time unit of the whole trace) would mean that the trace import is much longer. Still, I am ready to pay that price as it is much more convenient approach.

**Comment by dosimont** [comment]
Hi Luka. The time unit field is only a way to specify the unit for trace formats whose this information is not explicited, such as Pajé. It does not influence the import time.

**Comment by generoso** [comment]
This issue was moved to soctrace-inria/framesoc.importers#35
