### ISSUE TITLE
PJdump export makes framesoc crash

### ISSUE THREAD

**Issue by dbeniamine** [soctrace-inria/framesoc#190]
Hi,

I'm trying to export this [trace](https://github.com/soctrace-inria/framesoc/files/148490/trace.zip) (Import each file with Moca importer, with both trim lone producer and keep only accesses in data structure checked) to pjdump, but it makes framesoc crash after a few seconds.

I have the following log in the console:

    Settings values:
    
    Cache activated: true
    Cache directory: /home/david/Work/soctrace/runtime-EclipseApplication/ocelotlCache
    Cache size: -1
    Snapshot directory: /home/david/Work/soctrace/runtime-EclipseApplication/ocelotlSnapshot
    Cache Policy: CACHEPOLICY_FAST
    Cache Time slices: 900
    4 Metrics detected:
        Event Occurences [ALL] [PARTS, PROPORTIONS, MODE, EVENTMODE]
        State Total Duration [ALL] [PARTS, PROPORTIONS, MODE, STATEMODE]
        State Average Duration [ALL] [PARTS, PROPORTIONS, MODE, STATEMODE]
        Variable Average Value [ALL] [PARTS, PROPORTIONS, VARIABLEMODE]
    2 Data aggregation operators detected:
        Temporal Aggregation [PARTS, PROPORTIONS, STATEMODE, EVENTMODE, VARIABLEMODE][OLP_3D]
        Spatiotemporal Aggregation [PARTS, STATEMODE, EVENTMODE, VARIABLEMODE][DLP_2D_Leaf]
    8 Visualizations detected:
        Temporal Partition [PARTS] [OLP_3D]
        Temporal Stacked Bar Chart [PROPORTIONS] [OLP_3D]
        Spatiotemporal Partition [PARTS] [DLP_2D, DLP_2D_Leaf]
        Spatiotemporal State Mode [STATEMODE] [DLP_2D, DLP_2D_Leaf]
        Spatiotemporal Event Mode [EVENTMODE] [DLP_2D, DLP_2D_Leaf]
        Spatiotemporal Variable Mode [VARIABLEMODE] [DLP_2D, DLP_2D_Leaf]
        Temporal Mode Event [EVENTMODE] [OLP_3D]
        Temporal Mode State [STATEMODE] [OLP_3D]
    5 Statistics aggregation operators detected:
        Quantity of Events [EVENT_SUM] [OLP_3D, DLP_2D, DLP_2D_Leaf]
        State Total Duration [STATE_SUM] [OLP_3D, DLP_2D]
        State Total Duration (only Leaves) - Temporal [STATE_SUM] [OLP_3D]
        State Total Duration (only Leaves) - Spatiotemporal) [STATE_SUM] [DLP_2D, DLP_2D_Leaf]
        State Total Duration (only Active Producers) [STATE_SUM] [OLP_3D, DLP_2D]
    Found Moca_matrix_bloc_replacemalloc_20160224_183355_CET_Virtual in /home/david/Work/soctrace/runtime-EclipseApplication/ocelotlCache/Moca_matrix_bloc_replacemalloc_20160224_183355_CET_Virtual_8/Moca_matrix_bloc_replacemalloc_20160224_183355_CET_Virtual_8_Variable Average Value_24-02-2016 183840 CET.otlcache, Variable Average Value, Spatiotemporal Variable Mode, 1, 170297
    Size of the current cache is: 193468803 bytes (193 MB).
    [DICHOTOMY CACHE] Size of the current cache is: 0 bytes (0 MB).
    Size of the current cache is: 193468803 bytes (193 MB).
    [DICHOTOMY CACHE] Size of the current cache is: 0 bytes (0 MB).
    Size of the current cache is: 193468803 bytes (193 MB).
    [DICHOTOMY CACHE] Size of the current cache is: 0 bytes (0 MB).
    Size of the current cache is: 193468803 bytes (193 MB).
    [DICHOTOMY CACHE] Size of the current cache is: 0 bytes (0 MB).
    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0x00007f292af2d58a, pid=3508, tid=139814800213760
    #
    # JRE version: Java(TM) SE Runtime Environment (7.0_80-b15) (build 1.7.0_80-b15)
    # Java VM: Java HotSpot(TM) 64-Bit Server VM (24.80-b11 mixed mode linux-amd64 compressed oops)
    # Problematic frame:
    # C  [sqlite-3.7.2-libsqlitejdbc.so+0xf58a]  sqlite3_os_end+0x661
    #
    # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    #
    # An error report file with more information is saved as:
    # /home/david/hs_err_pid3508.log
    #
    # If you would like to submit a bug report, please visit:
    #   http://bugreport.java.com/bugreport/crash.jsp
    # The crash happened outside the Java Virtual Machine in native code.
    # See problematic frame for where to report the bug.

And there is the report file create by eclipse: [hs_err_pid3508.log.txt](https://github.com/soctrace-inria/framesoc/files/148492/hs_err_pid3508.log.txt).

David

**Comment by ycorre** [comment]
I did not managed to import the moca trace you provided: It fails with the following error "_For input string: "@Virt"_" and the following log:

```
java.lang.NumberFormatException: For input string: "@Virt"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at fr.inria.soctrace.tools.importer.moca.core.MocaParser.parseEventProd(MocaParser.java:606)
	at fr.inria.soctrace.tools.importer.moca.core.MocaParser.parseTrace(MocaParser.java:241)
	at fr.inria.soctrace.tools.importer.moca.MocaImporter$MocaImporterPluginJobBody.run(MocaImporter.java:118)
	at fr.inria.soctrace.framesoc.core.tools.management.PluginToolJob.run(PluginToolJob.java:76)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

```

**Comment by dbeniamine** [comment]
Sorry I put the wrong file in the archive, there is the right  [trace.zip](https://github.com/soctrace-inria/framesoc/files/148648/trace.zip).

Still the error is weird, it looks like the parser tried actually parse the header line while it should be dismissed, can you check that you have the last version of the importer ?
commit: 0cb8b3e659a91d3429ad8178a403e19ac4116762

**Comment by ycorre** [comment]
I have pushed a new version of framesoc (and of framesoc.importer, although it was not at fault here) that should fix the issue. 

(And the error I had with the moca importer was beacause the file containing the events had the wrong name and was thus processed as a file containing event producers).

**Comment by dbeniamine** [comment]
Hi,

Thanks for your answers, it seems to work here :)

David
